### ISSUE TITLE
helm install is broken

### ISSUE THREAD

**Issue by till** [ddosify/alaz#25]
We wanted to try out ddosify/alaz and ran into an issue:

```
Release "alaz" does not exist. Installing it now.
Error: DaemonSet in version "v1" cannot be handled as a DaemonSet: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
Error: Process completed with exit code 1.
```

Is there a minimum k8s version or something that is required to run alaz?

I was running the following commands:

```yaml
    - run: helm repo add ddosify https://ddosify.github.io/ddosify-helm-charts/
    - run: helm repo update
    - run: kubectl create namespace ddosify
    - run: helm upgrade --install --namespace ddosify alaz ddosify/alaz --set monitoringID=$MONITORING_ID
```

The error is from the last line.

**Comment by fatihbaltaci** [comment]
Hi @till, could you please share your Kubernetes environment (EKS, AKS, ...) and version? So I can reproduce the issue.

**Comment by till** [comment]
@fatihbaltaci yeah, thanks for responding:

```
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5+k0s", GitCommit:"93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c", GitTreeState:"clean", BuildDate:"2023-08-28T10:02:52Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```

This is not EKS/AKS, etc. — it's [k0s](https://docs.k0sproject.io/v1.27.5+k0s.0/) running on a couple nodes. Fairly basic.

The client is `1.27.5` as well, and helm is `v3.6.3`.

**Comment by till** [comment]
I ran helm (locally) with `--debug`:

```
history.go:56: [debug] getting history for release alaz
upgrade.go:153: [debug] preparing upgrade for alaz
false
upgrade.go:161: [debug] performing update for alaz
upgrade.go:355: [debug] creating upgraded release for alaz
client.go:393: [debug] checking 4 resources for changes
client.go:684: [debug] Looks like there are no changes for ServiceAccount "alaz-serviceaccount"
client.go:684: [debug] Looks like there are no changes for ClusterRole "alaz-role"
client.go:684: [debug] Looks like there are no changes for ClusterRoleBinding "alaz-role-binding"
upgrade.go:467: [debug] warning: Upgrade "alaz" failed: failed to create resource: DaemonSet in version "v1" cannot be handled as a DaemonSet: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
Error: UPGRADE FAILED: failed to create resource: DaemonSet in version "v1" cannot be handled as a DaemonSet: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
helm.go:84: [debug] DaemonSet in version "v1" cannot be handled as a DaemonSet: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
failed to create resource
helm.sh/helm/v3/pkg/kube.(*Client).Update.func1
	helm.sh/helm/v3/pkg/kube/client.go:410
helm.sh/helm/v3/pkg/kube.ResourceList.Visit
	helm.sh/helm/v3/pkg/kube/resource.go:32
helm.sh/helm/v3/pkg/kube.(*Client).Update
	helm.sh/helm/v3/pkg/kube/client.go:394
helm.sh/helm/v3/pkg/action.(*Upgrade).releasingUpgrade
	helm.sh/helm/v3/pkg/action/upgrade.go:409
runtime.goexit
	runtime/asm_amd64.s:1650
UPGRADE FAILED
main.newUpgradeCmd.func2
	helm.sh/helm/v3/cmd/helm/upgrade.go:229
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.7.0/command.go:940
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.7.0/command.go:992
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:267
runtime.goexit
	runtime/asm_amd64.s:1650
```

**Comment by fatihbaltaci** [comment]
Thank you, @till, for reporting. I'll let you know once I try out with k0s.

**Comment by till** [comment]
@fatihbaltaci before you go down this route, I think the error is somewhere here:
https://github.com/ddosify/ddosify-helm-charts/blob/master/charts/alaz/templates/daemonset.yaml#L23-L38

And I am guessing triggered by:
https://github.com/ddosify/ddosify-helm-charts/blob/master/charts/alaz/values.yaml#L20-L24

I am going to try quoting the values and see if that helps.

**Comment by fatihbaltaci** [comment]
Yes, the old version of Alaz uses quotes for boolean environment values: 

```
        - name: METRICS_BACKEND
          value: "true"
        - name: EBPF_ENABLED
          value: "true"
```

Please let me know if it works.

**Comment by till** [comment]
@fatihbaltaci made a PR if you want to look. Do you think that you could release a new version?

**Comment by till** [comment]
And maybe a linter of some kind or a test install in that repository would be a good idea?

**Comment by fatihbaltaci** [comment]
@till I will check your PR with other Kubernetes environments, and if it is ok, I will merge your PR. Thanks. 

> And maybe a linter of some kind or a test install in that repository would be a good idea?

Can you give some more details?

**Comment by till** [comment]
@fatihbaltaci as in setup a k8s on github actions ([1](https://github.com/helm/kind-action), [2](https://docs.k0sproject.io/v0.13.1/k0s-in-docker/)) and deploy the chart so you know it works?

I am not sure what else people do for helm to test their manifests, I am not even sure if `helm lint` is smart enough to catch this.

In the end, I didn't expect to troubleshoot your helm chart when testing your product.

**Comment by fatihbaltaci** [comment]
This issue seems specific to k0s since it runs without issue on EKS, Openshift, AKS, and Microk8s. After testing your PR, it appears to be working. And I'll take a look at your suggestions. 

Thanks for your contribution.

**Comment by fatihbaltaci** [comment]
The new helm chart version is released: https://github.com/ddosify/ddosify-helm-charts/releases/tag/alaz-0.2.3

@till Is there any problem with this release?
