### ISSUE TITLE
Alaz is not up and running

### ISSUE THREAD

**Issue by QAInsights** [ddosify/alaz#27]
I am trying to get started with ddosify o11y to monitor my k8s cluster. Upon following the commands, I am getting the below error in the daemon set logs.

```
{"level":"info","tag":"v0.1.4","time":1696821124,"message":"alaz tag"}
{"level":"info","time":1696821124,"message":"k8sCollector initializing..."}
{"level":"fatal","error":"field InetSockSetState: program inet_sock_set_state: apply CO-RE relocations: no BTF found for kernel version 6.4.16-linuxkit: not supported","time":1696821124,"message":"loading objects"}
```

K8S details:

```
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.2
```

Command issues

```
# Deploy Alaz with Kubectl
MONITORING_ID=<redacted>
curl -sSL https://raw.githubusercontent.com/ddosify/alaz/master/resources/alaz.yaml -o alaz.yaml
sed -i"" -e "s/<MONITORING_ID>/$MONITORING_ID/g" alaz.yaml
kubectl create namespace ddosify
kubectl apply -f alaz.yaml

```

**Comment by kenanfarukcakir** [comment]
Hey, thanks for trying ddosify!
It seems your kernel is not compiled with BTF. Alaz requires kernels to be built with BTF info rn. But we plan to support all kernel versions in the future. Could you also share your Linux distribution and its version in order for us to test later on ?

You can check the limitations section on [readme](https://github.com/ddosify/alaz#limitations).
